DROP DATABASE IF EXISTS `movie-hunter`;

CREATE DATABASE IF NOT EXISTS `movie-hunter`;

USE `movie-hunter`;

CREATE TABLE CITY (
	CITY_ID INT(4) NOT NULL AUTO_INCREMENT,
	CITY_NAME VARCHAR(20) NOT NULL,
	CITY_STATE VARCHAR(10) NOT NULL,
	CITY_PIN INT(6) NOT NULL,
	CONSTRAINT PK_CITY_ID PRIMARY KEY (CITY_ID)
) ENGINE=InnoDB;

ALTER TABLE CITY AUTO_INCREMENT = 1;

CREATE TABLE THEATRE (
	THEATRE_ID INT(4) NOT NULL AUTO_INCREMENT,
	THEATRE_NAME INT(10) NOT NULL,
	THEATRE_SCREENS DECIMAL(10,2) NOT NULL,
    THEATRE_CITY_ID INT(4) NOT NULL,
	CONSTRAINT PK_THEATRE_ID PRIMARY KEY (THEATRE_ID),
  	CONSTRAINT FK_THEATRE_CITY_ID FOREIGN KEY (THEATRE_CITY_ID) REFERENCES CITY (CITY_ID)
) ENGINE=InnoDB;

ALTER TABLE THEATRE AUTO_INCREMENT = 1;

CREATE TABLE MOVIE (
	MOVIE_ID INT(4) NOT NULL AUTO_INCREMENT,
	MOVIE_TITLE VARCHAR(10) NOT NULL,
	MOVIE_DESCRIPTION VARCHAR(40) NOT NULL,
	DURATION DECIMAL(2,2) NOT NULL,
    LANG VARCHAR(16) NOT NULL,
    RELEASE_DATE DATETIME,
    COUNTRY VARCHAR(64) NOT NULL,
    GENERE VARCHAR(20) NOT NULL,
	CONSTRAINT PK_MOVIE_ID PRIMARY KEY (MOVIE_ID)
) ENGINE=InnoDB;

ALTER TABLE MOVIE AUTO_INCREMENT = 1;

CREATE TABLE SCREEN (
	SCREEN_ID INT(4) NOT NULL AUTO_INCREMENT,
    SCREEN_NAME VARCHAR(64) NOT NULL,
    TOTAL_SEATS INT(4) NULL NULL,
    SCREEN_THEATRE_ID INT(4) NOT NULL,
    CONSTRAINT PK_SCREEN_ID PRIMARY KEY (SCREEN_ID),
    CONSTRAINT FK_SCREEN_THEATRE_ID FOREIGN KEY (SCREEN_THEATRE_ID) REFERENCES THEATRE (THEATRE_ID)
) ENGINE=InnoDB;

ALTER TABLE SCREEN AUTO_INCREMENT = 1;


CREATE TABLE SCREEN_SEAT (
	SCREEN_SEAT_ID INT(4) NOT NULL AUTO_INCREMENT,
    SEAT_NUMBER VARCHAR(64) NOT NULL,
    SEAT_TYPE INT(4) NULL NULL,
    SCREEN_THEATRE_SEAT_ID INT(4) NOT NULL,
    CONSTRAINT PK_SCREEN_SEAT_ID PRIMARY KEY (SCREEN_SEAT_ID),
    CONSTRAINT FK_SCREEN_THEATRE_SEAT_ID FOREIGN KEY (SCREEN_THEATRE_SEAT_ID) REFERENCES SCREEN (SCREEN_ID)
) ENGINE=InnoDB;

ALTER TABLE SCREEN_SEAT AUTO_INCREMENT = 1;


CREATE TABLE MOVIE_SHOW (
	MOVIE_SHOW_ID INT(4) NOT NULL AUTO_INCREMENT,
    MOVIE_SHOW_DATE DATETIME NOT NULL,
    MOVIE_SHOW_STARTTIME DATETIME NULL NULL,
    MOVIE_SHOW_ENDTIME DATETIME NOT NULL,
    MOVIE_SHOW_THEATRE_ID INT(4) NOT NULL,
    MOVIE_SHOW_MOVIE_ID INT(4) NOT NULL,
    CONSTRAINT PK_MOVIE_SHOW_ID PRIMARY KEY (MOVIE_SHOW_ID),
    CONSTRAINT FK_MOVIE_SHOW_THEATRE_ID FOREIGN KEY (MOVIE_SHOW_THEATRE_ID) REFERENCES THEATRE (THEATRE_ID),
    CONSTRAINT FK_MOVIE_SHOW_MOVIE_ID FOREIGN KEY (MOVIE_SHOW_MOVIE_ID) REFERENCES MOVIE (MOVIE_ID)
) ENGINE=InnoDB;

ALTER TABLE MOVIE_SHOW AUTO_INCREMENT = 1;


CREATE TABLE USERS (
	USERS_ID INT(4) NOT NULL AUTO_INCREMENT,
    USERS_NAME VARCHAR(64) NOT NULL,
    USERS_PASSWORD VARCHAR(64) NULL NULL,
    USERS_EMAIL VARCHAR(64) NOT NULL,
    USERS_PHONE INT(10) NOT NULL,
    CONSTRAINT PK_USERS_ID PRIMARY KEY (USERS_ID)
) ENGINE=InnoDB;

ALTER TABLE USERS AUTO_INCREMENT = 1;


CREATE TABLE BOOKING (
	BOOKING_ID INT(4) NOT NULL AUTO_INCREMENT,
    NO_OF_SEATS INT(2) NOT NULL,
    TIME_OF_BOOKING DATETIME NULL NULL,
    BOOKING_STATUS DATETIME NOT NULL,
    BOOKING_USER_ID INT(4) NOT NULL,
    BOOKING_MOVIE_SHOW_ID INT(4) NOT NULL,
    CONSTRAINT PK_BOOKING_ID PRIMARY KEY (BOOKING_ID),
    CONSTRAINT FK_BOOKING_USER_ID FOREIGN KEY (BOOKING_USER_ID) REFERENCES USERS (USERS_ID),
    CONSTRAINT FK_BOOKING_MOVIE_SHOW_ID FOREIGN KEY (BOOKING_MOVIE_SHOW_ID) REFERENCES MOVIE_SHOW (MOVIE_SHOW_ID)
) ENGINE=InnoDB;

ALTER TABLE BOOKING AUTO_INCREMENT = 1;


CREATE TABLE SHOW_SEAT (
	SHOW_SEAT_ID INT(4) NOT NULL AUTO_INCREMENT,
    SHOW_SEAT_STATUS INT(2) NOT NULL,
    PRICE DECIMAL(4,2) NULL NULL,
    BOOKING_STATUS DATETIME NOT NULL,
    SCREEN_SEAT_ID INT(4) NOT NULL,
    MOVIE_SHOW_ID INT(4) NOT NULL,
    BOOKING_ID INT(4) NOT NULL,
    CONSTRAINT PK_SHOW_SEAT_ID PRIMARY KEY (SHOW_SEAT_ID),
    CONSTRAINT FK_SCREEN_SEAT_ID FOREIGN KEY (SCREEN_SEAT_ID) REFERENCES SCREEN_SEAT (SCREEN_SEAT_ID),
    CONSTRAINT FK_MOVIE_SHOW_ID FOREIGN KEY (MOVIE_SHOW_ID) REFERENCES MOVIE_SHOW (MOVIE_SHOW_ID),
    CONSTRAINT FK_BOOKING_ID FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING (BOOKING_ID)
) ENGINE=InnoDB;

ALTER TABLE SHOW_SEAT AUTO_INCREMENT = 1;

CREATE TABLE PAYMENT (
	PAYMENT_ID INT(4) NOT NULL AUTO_INCREMENT,
    AMOUNT DECIMAL(4,2) NOT NULL,
    PAYMENT_TIME DATETIME NULL NULL,
    DISCOUNT_COUPON_ID INT(4) NOT NULL,
    TRANSACTION_ID INT(4) NOT NULL,
    PAYMENT_METHOD INT(4) NOT NULL,
    PAYMENT_BOOKING_ID INT(4) NOT NULL,
    CONSTRAINT PK_PAYMENT_ID PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT FK_PAYMENT_BOOKING_ID FOREIGN KEY (PAYMENT_BOOKING_ID) REFERENCES BOOKING (BOOKING_ID)
) ENGINE=InnoDB;

ALTER TABLE PAYMENT AUTO_INCREMENT = 1;