spring:
   application:
      name: user-management-service

server:
  port: 2222

eureka:
  client:
    serviceUrl:
      defaultUrl: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

