spring:
   application:
      name: router-service

server:
  port: 1111

eureka:
  client:
    serviceUrl:
      defaultUrl: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

