spring:
   application:
      name: movie-management-service

server:
  port: 3333

eureka:
  client:
    serviceUrl:
      defaultUrl: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

